Experiment_name: ntu60_ShiftGCN_joint_xsub_seen55_unseen5

# feeder
feeder: feeders.feeder_ntu.Feeder_Shiftgcn_Pretrain
train_feeder_args:
  data_path: /root/autodl-tmp/Neuron/data/ntu60/NTU60_CS.npz
  split: train
  ntu_task: ntu60_xsub
  zero_spilt_setting: ntu60_seen55_unseen5
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64  
  normalization: False
  random_rot: True  
  p_interval: [0.5, 1]
  vel: False
  bone: False
test_feeder_args:
  data_path: /root/autodl-tmp/Neuron/data/ntu60/NTU60_CS.npz
  split: test
  ntu_task: ntu60_xsub
  zero_spilt_setting: ntu60_seen55_unseen5
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False



# model
model: model.shift_gcn.Model
model_args:
  num_class: 55
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 110
nesterov: True