work_dir: ./work_dir/pkuv1_xsub_46_5split/zsl

# feeder
feeder: feeders.feeder_pku.Feeder_Shiftgcn_Match

train_feeder_args:
  data_path: data/pkummd/part1/pkuv1_xsub.npz
  pku_task: pkuv1_xsub
  zero_spilt_setting: pkuv1_seen46_unseen5
  zero_setting: ZSL
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_zsl_args:
  data_path: data/pkummd/part1/pkuv1_xsub.npz
  pku_task: pkuv1_xsub
  zero_spilt_setting: pkuv1_seen46_unseen5
  zero_setting: ZSL
  split: test
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_gzsl_args:
  data_path: data/pkummd/part1/pkuv1_xsub.npz
  pku_task: pkuv1_xsub
  zero_spilt_setting: pkuv1_seen46_unseen5
  zero_setting: GZSL
  split: test
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

# model
model: model.shiftgcn_match.ModelMatch
weights: model/pkummdv1_ShiftGCN_joint_xsub_seen46_unseen5-81-43870.pt
# text feature
text_path: semantic_feature/pkuv1_part_descriptions_token.tar
pool_path: semantic_feature/joints_concept_pool.tar
# task
task_name: pkuv1_seen46_unseen5

model_args:
  num_class: 51
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  body_part: 6
  motion: 100
  unseen: 46
  project_dim: 128
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005   
base_lr: 0.1  
lr_decay_rate: 0.1
step: [30, 40]   
warm_up_epoch: 0
temperature_rate: 0.8 
calibration_factor: [[0, 0], [0.02, 0.02], [1.0, 1.0]]  



# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 50 
nesterov: True

